'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.235
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar de My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("P")>  _
        Public ReadOnly Property Red() As String
            Get
                Return CType(Me("Red"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0.0.0")>  _
        Public Property IP() As String
            Get
                Return CType(Me("IP"),String)
            End Get
            Set
                Me("IP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("27851")>  _
        Public Property Puerto() As Integer
            Get
                Return CType(Me("Puerto"),Integer)
            End Get
            Set
                Me("Puerto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.0.1")>  _
        Public Property IpLlamar() As String
            Get
                Return CType(Me("IpLlamar"),String)
            End Get
            Set
                Me("IpLlamar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property llamarAlInicio() As Boolean
            Get
                Return CType(Me("llamarAlInicio"),Boolean)
            End Get
            Set
                Me("llamarAlInicio") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TES")>  _
        Public Property Entorno() As String
            Get
                Return CType(Me("Entorno"),String)
            End Get
            Set
                Me("Entorno") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property CuentaComercioPAS() As Integer
            Get
                Return CType(Me("CuentaComercioPAS"),Integer)
            End Get
            Set
                Me("CuentaComercioPAS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SELECT     TOP 800 dbo.CUENTASCLIENTES_ESTADOS.Descripcion AS Expr1, dbo.AUTORIZA"& _ 
            "CIONES_ESTADOS.Descripcion,                       dbo.AUTORIZACIONES.IdAutorizac"& _ 
            "ion, dbo.AUTORIZACIONES.Fecha, dbo.AUTORIZACIONES.IdCuentaComercio, dbo.CUENTASC"& _ 
            "OMERCIOS.NFantasia,                 dbo.AUTORIZACIONES.IdPlastico, dbo.AUTORIZAC"& _ 
            "IONES.NroAutorizacion, dbo.AUTORIZACIONES.CantidadCuotas, dbo.AUTORIZACIONES.Mon"& _ 
            "toTotal,                       dbo.AUTORIZACIONES.Motivo, dbo.AUTORIZACIONES.IdT"& _ 
            "ransaccion, dbo.AUTORIZACIONES.NroCupon, dbo.AUTORIZACIONES.LimCompra,          "& _ 
            "             dbo.AUTORIZACIONES.LimCompraCuotas, dbo.AUTORIZACIONES.LimAdelanto,"& _ 
            " dbo.AUTORIZACIONES.DispCompra,                       dbo.AUTORIZACIONES.DispCom"& _ 
            "praCuotas, dbo.AUTORIZACIONES.DispAdelanto, dbo.AUTORIZACIONES.IdPlanVenta,     "& _ 
            "                 dbo.AUTORIZACIONES.IdTipoTransaccion, dbo.AUTORIZACIONES.ISOCod"& _ 
            "igoResultado, dbo.AUTORIZACIONES.FechaNegocio,                       dbo.AUTORIZ"& _ 
            "ACIONES.Trace, dbo.AUTORIZACIONES.MontoOriginal, dbo.AUTORIZACIONES.FechaAcceso,"& _ 
            " dbo.PLASTICOS.IdEstadoPlastico,                       dbo.CUENTASCLIENTES.IdCue"& _ 
            "ntaCliente, dbo.PLASTICOS.Track1, dbo.CUENTASCLIENTES.CacheDisponibleCompra,    "& _ 
            "                   dbo.CUENTASCLIENTES.CacheDisponibleCompraCuotas, dbo.CUENTASC"& _ 
            "LIENTES.CacheFecha, dbo.CUENTASCLIENTES.CacheDisponibleAdelanto,                "& _ 
            "       dbo.TERMINALES.Codigo, dbo.TERMINALES.Descripcion AS Expr2 FROM         d"& _ 
            "bo.AUTORIZACIONES INNER JOIN                      dbo.AUTORIZACIONES_ESTADOS ON "& _ 
            "dbo.AUTORIZACIONES.IdEstadoAutorizacion = dbo.AUTORIZACIONES_ESTADOS.IdEstadoAut"& _ 
            "orizacion INNER JOIN                       dbo.PLASTICOS ON dbo.AUTORIZACIONES.I"& _ 
            "dPlastico = dbo.PLASTICOS.IdPlastico INNER JOIN                     dbo.CUENTASC"& _ 
            "LIENTES ON dbo.PLASTICOS.IdCuentaCliente = dbo.CUENTASCLIENTES.IdCuentaCliente I"& _ 
            "NNER JOIN                       dbo.TERMINALES ON dbo.AUTORIZACIONES.IdTerminal "& _ 
            "= dbo.TERMINALES.IdTerminal AND                       dbo.AUTORIZACIONES.IdTipoT"& _ 
            "erminal = dbo.TERMINALES.IdTipoTerminal INNER JOIN dbo.CUENTASCOMERCIOS ON dbo.A"& _ 
            "UTORIZACIONES.IdCuentaComercio = dbo.CUENTASCOMERCIOS.IdCuentaComercio INNER JOI"& _ 
            "N                       dbo.CUENTASCLIENTES_ESTADOS ON                       dbo"& _ 
            ".CUENTASCLIENTES.IdEstadoCuentaCliente = dbo.CUENTASCLIENTES_ESTADOS.IdEstadoCue"& _ 
            "ntaCliente WHERE     dbo.AUTORIZACIONES.IdTipoTerminal IN ( 3) ORDER BY dbo.AUTO"& _ 
            "RIZACIONES.IdAutorizacion DESC")>  _
        Public Property SQLAutorizaciones() As String
            Get
                Return CType(Me("SQLAutorizaciones"),String)
            End Get
            Set
                Me("SQLAutorizaciones") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("gustavo.marzioni@cfr.com.ar")>  _
        Public Property EmailAvisoMaximo() As String
            Get
                Return CType(Me("EmailAvisoMaximo"),String)
            End Get
            Set
                Me("EmailAvisoMaximo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
        Public Property MontoAviso() As Integer
            Get
                Return CType(Me("MontoAviso"),Integer)
            End Get
            Set
                Me("MontoAviso") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("operaciones@tarjetanexo.com.ar")>  _
        Public Property FromEmail() As String
            Get
                Return CType(Me("FromEmail"),String)
            End Get
            Set
                Me("FromEmail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mail.cfr.com.ar")>  _
        Public Property Servidor() As String
            Get
                Return CType(Me("Servidor"),String)
            End Get
            Set
                Me("Servidor") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property CuentaComercio() As Integer
            Get
                Return CType(Me("CuentaComercio"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public ReadOnly Property TipoTransaccionAdel1pago() As Short
            Get
                Return CType(Me("TipoTransaccionAdel1pago"),Short)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("33")>  _
        Public ReadOnly Property TipoTransaccionAdelCtas() As Short
            Get
                Return CType(Me("TipoTransaccionAdelCtas"),Short)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public ReadOnly Property IdPlanAdelCtas() As Integer
            Get
                Return CType(Me("IdPlanAdelCtas"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public ReadOnly Property TipoTransaccionPAS() As Short
            Get
                Return CType(Me("TipoTransaccionPAS"),Short)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public ReadOnly Property IdPlanPAS() As Integer
            Get
                Return CType(Me("IdPlanPAS"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public ReadOnly Property TipotransaccionPulsos() As Short
            Get
                Return CType(Me("TipotransaccionPulsos"),Short)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public ReadOnly Property MaxCuotasInformativo() As Integer
            Get
                Return CType(Me("MaxCuotasInformativo"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4000")>  _
        Public Property MontoMaxAdelanto() As Integer
            Get
                Return CType(Me("MontoMaxAdelanto"),Integer)
            End Get
            Set
                Me("MontoMaxAdelanto") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("122")>  _
        Public ReadOnly Property TipoTransaccionDevolucion() As Short
            Get
                Return CType(Me("TipoTransaccionDevolucion"),Short)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public ReadOnly Property TipoTransaccionCompra() As Short
            Get
                Return CType(Me("TipoTransaccionCompra"),Short)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public ReadOnly Property Auditar() As Boolean
            Get
                Return CType(Me("Auditar"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("gustavo.marzioni@cfr.com.ar")>  _
        Public Property EmailAvisoSAF() As String
            Get
                Return CType(Me("EmailAvisoSAF"),String)
            End Get
            Set
                Me("EmailAvisoSAF") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property AdelantoenCuotasAfectaLimiteCompraCuotas() As Boolean
            Get
                Return CType(Me("AdelantoenCuotasAfectaLimiteCompraCuotas"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property CantidadMaxAdelantos() As Short
            Get
                Return CType(Me("CantidadMaxAdelantos"),Short)
            End Get
            Set
                Me("CantidadMaxAdelantos") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4000")>  _
        Public ReadOnly Property EsperaMaxima() As Integer
            Get
                Return CType(Me("EsperaMaxima"),Integer)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("gustavo.marzioni@cfr.com.ar")>  _
        Public Property EmailNoeco() As String
            Get
                Return CType(Me("EmailNoeco"),String)
            End Get
            Set
                Me("EmailNoeco") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public ReadOnly Property TipotransaccionPago() As Short
            Get
                Return CType(Me("TipotransaccionPago"),Short)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MensajeSAldo() As Boolean
            Get
                Return CType(Me("MensajeSAldo"),Boolean)
            End Get
            Set
                Me("MensajeSAldo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property IdEnteCobranza() As Short
            Get
                Return CType(Me("IdEnteCobranza"),Short)
            End Get
            Set
                Me("IdEnteCobranza") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public ReadOnly Property HabilitarTopePlastico() As Boolean
            Get
                Return CType(Me("HabilitarTopePlastico"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property activarNolock() As Boolean
            Get
                Return CType(Me("activarNolock"),Boolean)
            End Get
            Set
                Me("activarNolock") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property RegistrarConsultasLentas() As Boolean
            Get
                Return CType(Me("RegistrarConsultasLentas"),Boolean)
            End Get
            Set
                Me("RegistrarConsultasLentas") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("operacionescfr")>  _
        Public ReadOnly Property EmailUsuario() As String
            Get
                Return CType(Me("EmailUsuario"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("irbksa")>  _
        Public ReadOnly Property EmailPwd() As String
            Get
                Return CType(Me("EmailPwd"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ONLINETARJETA.My.MySettings
            Get
                Return Global.ONLINETARJETA.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
